### PR TITLE
update changes to the template file

### PR DESCRIPTION
**Pull request by shayan823**

### CODE REVIEW

**Comment by sanjayankur31** [comment]
So we're just making sure that the background for the channel notes is white---was this causing an issue (with GitHub dark mode?)

**Comment by shayan823** [comment]
I tried adding the channel notes in a <div> tag as well. Actually, the line breaks in the notes of the neuroml file are not allowing the images to render properly. 
When tried adding max-width=120px to the <td> it wasnt helping so I reverted it back. 

Currently, the images are rendered properly except that the text in the first column is wrapped. Have a look at [this](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/tree/issue_12_test/NeuroML2/channel_summary).

**Comment by pgleeson** [comment]
@shayan823 Just to clarify, are you saying this is a fix already or still being tested?

**Comment by shayan823** [comment]
It's still being tested. As its fails to render the image when we have line breaks in the notes. 
We can parse the channel NeuroML files such that notes have no line breaks keeping the template as it is now.

**Comment by pgleeson** [comment]
FYI the use of `<sup>` was a quick and dirty hack to allow small text for the longish descriptions. There is certainly a better way to do that which may give less problems...

**Pull request merged**
