### PR TITLE
pynml-archive: add `-sedml`

### PR DESCRIPTION
**Pull request by sanjayankur31**

### CODE REVIEW

**Comment by sanjayankur31** [comment]
@pgleeson : do we have a different format string for LEMS? I can't find one. This is what the manifest current looks like:


``` xml
<?xml version="1.0" encoding="utf-8"?>
<omexManifest xmlns="http://identifiers.org/combine.specifications/omex-manifest">
        <content location="." format="http://identifiers.org/combine.specifications/omex"/>
        <content location="LEMS_NML2_Ex5_DetCell.sedml" master="true" format="http://identifiers.org/combine.specifications/sed-ml"/>
        <content location="LEMS_NML2_Ex5_DetCell.xml"  format="http://identifiers.org/combine.specifications/neuroml"/>
        <content location="NaConductance.channel.nml"  format="http://identifiers.org/combine.specifications/neuroml"/>
        <content location="KConductance.channel.nml"  format="http://identifiers.org/combine.specifications/neuroml"/>
        <content location="LeakConductance.channel.nml"  format="http://identifiers.org/combine.specifications/neuroml"/>
        <content location="NML2_SingleCompHHCell.nml"  format="http://identifiers.org/combine.specifications/neuroml"/>
</omexManifest>

```

**Comment by pgleeson** [comment]
Not sure... might be best to run an example model on the biosim website and then try to down load the omex file...  
What I noticed was it didn't like *neux files, and also seemed to want a metadata file in there too, with rdf. Not sure what goes in that that's not in the manifest...

**Comment by sanjayankur31** [comment]
I'll try downloading an example to see what they do.

In the meantime, I've tweaked it so that if the master file is sedml, the archive will be *.omex. Will check what the rdf file includes---that isn't implemented at the moment.

**Comment by sanjayankur31** [comment]
Also verified with `pynml -validate-sedml` now:

```
$ pynml -validate-sedm LEMS_model.sedml
line 181: (10302 [Error]) The value of a 'sedml:id' must conform to the syntax of the <sbml> data type 'SId'
Reference: L3V1 Sedml V1 Section
 The id on the <report> is 'results/ex5_v', which does not conform to the syntax.

line 187: (10302 [Error]) The value of a 'sedml:id' must conform to the syntax of the <sbml> data type 'SId'
Reference: L3V1 Sedml V1 Section
 The id on the <report> is 'results/ex5_vars', which does not conform to the syntax.


pyNeuroML >>> ERROR - one or more SEDML files failed to validate

```

**Review by pgleeson — APPROVED** [review]

**Pull request merged**
