### PR TITLE
added -validate-sbml option

### PR DESCRIPTION
**Pull request by robertvi**
Also added sbml section to options.extras_require and a test script at tests/sbml/test_sbml.py. Running the main test.sh was taking too long so am not sure it will correctly handle the test.

### CODE REVIEW

**Comment by sanjayankur31** [comment]
I'll tweak this to make it against development, since that's where the latest code lives.

**Comment by robertvi** [comment]
hopefully ready for review and merging now

**Comment by pgleeson** [comment]
Tested and looks good.

**Comment by sanjayankur31** [comment]
@all-contributors please add @robertvi for code,test

**Pull request merged**
