### PR TITLE
Refactored NML2ChannelAnalysis into components for integration with other modules (e.g. SciUnit)

### PR DESCRIPTION
**Pull request by rgerkin**

### CODE REVIEW

**Comment by rgerkin** [comment]
The pull request passes travis for versions 2.7 and 3.4.  It fails 2.6 to my use of a dictionary comprehension.  I propose ignoring this and removing 2.6 testing from travis.  2.6 is obsolete and no one uses it anyway: http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/

**Comment by pgleeson** [comment]
@rgerkin maybe it's better to just skip that test in test.sh. There should be a TravicCI env var for the python version...

**Comment by rgerkin** [comment]
So you are OK with having the Travis badge show failed, but you want the test.sh file to check the Python version before running?

**Comment by pgleeson** [comment]
No, I was suggesting wrap the failing command in test.sh with something like:

    if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ] ; then 
        pynml-channelanalysis NaConductance.channel.nml -nogui
    fi

so it runs all other tests in 2.6 still...

**Comment by rgerkin** [comment]
@pgleeson OK, done.

**Comment by pgleeson** [comment]
Thanks @rgerkin

**Pull request merged**
