### PR TITLE
Separated exec_in_dir from directory with LEMS file

### PR DESCRIPTION
**Pull request by rgerkin**
`reload_saved_data` now passes these two arguments separately instead of combining them through the `relative_path` function.  I think this will require `lems_file_name` to always be resolvable to the LEMS file (either a full path or correct path relative to the working directory) independently of the value of `exec_in_dir`.  I've always been doing this anyway, so if any other part of the code that I am not aware of isn't, that would also need to be changed.  

This was motivated by #41, which can be closed when this is accepted.

### CODE REVIEW

**Comment by pgleeson** [comment]
@rgerkin Thanks for this. It would be better though to still have the option of just specifying the lems file relative to the current dir as the only argument. What about having:
```
def reload_saved_data( lems_file_name,
                       base_dir='.', 
                       t_run=datetime(1900,1,1),
```
This would also have the advantage of not breaking existing code

**Comment by rgerkin** [comment]
@pgleeson I've made the requested changes.

**Comment by pgleeson** [comment]
Merged @rgerkin. Let me know if any other open issues of yours are proving bottlenecks...

**Comment by rgerkin** [comment]
@pgleeson Thanks.  When will you push 0.3.1 to pypi?  I'm down to just a few libraries that I am still installing from dependency links on github.

**Comment by pgleeson** [comment]
@rgerkin I've just put 0.3.1 on pypi. Let me know if you have any issues.

**Pull request merged**
