### PR TITLE
Add util functions to list recordables in a NeuroML model

### PR DESCRIPTION
**Pull request by sanjayankur31**
I think this is complete, but we'd probably be better off adding a few more unit tests with more complex examples just to be sure.

Depends on https://github.com/LEMS/pylems/pull/55 so the CI tests may fail at the moment.

Related task: update CI so that the dev branch uses the dev branches of the other tools.

### CODE REVIEW

**Comment by sanjayankur31** [comment]
Additional note: I've based this on top of https://github.com/NeuroML/pyNeuroML/pull/116, so that needs to be merged first

**Comment by pgleeson** [comment]
@sanjayankur31 Tests on this are still not passing. More prs need to be merged?

**Comment by sanjayankur31** [comment]
CI isn't installing pylems from development etc. for this PR. I'll sync it with development here again and see if that fixes it.

**Comment by sanjayankur31** [comment]
Won't let me push after the rebase. Closing this and opening a new PR.

**Pull request closed without merging**
